### PR TITLE
Extract user identity hook

### LINKED ISSUE #343: Access to saml_response during user creation
I am running a multi-tenant application that allows just-in-time provisioning when user accounts don't exist. Part of this requirement is that the user is assigned to the proper tenant once they are created in the system. 

Using the current hooks, `CREATE_USER`, `BEFORE_LOGIN`, and `AFTER_LOGIN`, I don't have access to any of the saml_response where I would derive the tenant that the user should be assigned to (specifically from the Issuer URL).

Is there a way that I can accomplish this with the existing triggers in the library?

### PR DESCRIPTION
**Pull request by mostafa**
Closes #343.

CC: @jeremylivingston Please test this and see if this solution works for you. Feel free to review it as well and provide feedback.

### CODE REVIEW

**Comment by jeremylivingston** [comment]
Wow, this is great. Thanks for putting this together!

Just tested it out and it appears to be working well for my use case. Just curious, is there a reason why the call to `create_new_user` in the library isn't supplied the user Dict as kwargs? This would simplify the creation of the new user and would prevent cases where the user is created in the `create_user` manager, but then fails to add other required data in the `CREATE_USER` trigger (something I encountered during testing).

The current solution still works well, but I was wondering if there was a reason that more data wasn't passed to the create_user call to accomplish something similar.

**Comment by mostafa** [comment]
@jeremylivingston The idea is that the library should create a bare minimum user and then let the user (i.e. developer) set it up later.

**Comment by jeremylivingston** [comment]
Makes sense. In my situation it can sometimes result in an orphaned user if there are problems with setup. The user will get created with no team assigned and the hook attempts to assign the team. If that step fails for some reason, it means the user is unable to login since they have no password and are not assigned to the correct team.

It's not a huge deal since I can set up the necessary logging to notify us when it happens, but it would be cleaner if I could access the enriched data in the create_user step.

Thanks again for all of your help with this!

**Comment by jeremylivingston** [comment]
Thanks again for this! Any chance you'd be willing to tag a new version containing this update?

**Comment by mostafa** [comment]
Will do tomorrow.

**Comment by bobflorian** [comment]
Thank you for this, this worked for me too!

**Pull request merged**
