### PR TITLE
Use settings.SAML2_AUTH in calls to dictor

### PR DESCRIPTION
**Pull request by syre**
This fixes the same problem as in https://github.com/grafana/django-saml2-auth/pull/19 really, as passing `settings` to `dictor` yields wrong results, i've tried to mirror the code.

Also uses the `accepted_time_diff` variable that is assigned above.

@mostafa are you able to take a look?

### CODE REVIEW

**Comment by mostafa** [comment]
Thanks, @syre for your contribution. Would you please update other instances in other files, too?

**Comment by syre** [comment]
You are welcome mostafa, the rest of the instances in `user.py` and `views.py` pass `settings.SAML2_AUTH` to dictor which is a dictionary, and not `settings` itself, so they should be okay.

**Comment by syre** [comment]
Alright i have updated the MR to use `dictor` and `saml2_auth_settings` everywhere else.

**Comment by sgabb** [comment]
+1 for this PR
With current version some settings always take the default values and not those set in django settings.

**Comment by mostafa** [comment]
@sgabb Are you sure about the default value issue? I think it isn't related to this PR.

**Comment by syre** [comment]
@sgabb @mostafa that is correct and related to this PR.

These would always use the default values previous to this MR:
`AUTHN_REQUESTS_SIGNED`
`LOGOUT_REQUESTS_SIGNED`
`WANT_ASSERTIONS_SIGNED`
`WANT_RESPONSE_SIGNED`

**Pull request merged**
